"""phan_quyen

Revision ID: 00c3e94587fa
Revises: 
Create Date: 2023-08-18 14:12:48.922113

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '00c3e94587fa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('show', sa.Boolean(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.Column('dynamic', sa.Boolean(), nullable=True),
    sa.Column('object', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('permission',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('resource', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('full_name', sa.String(length=100), nullable=True),
    sa.Column('type', sa.SmallInteger(), nullable=True),
    sa.Column('birthday', sa.DATE(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('created_date', mysql.INTEGER(unsigned=True), nullable=True),
    sa.Column('avatar_url', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('created_user_id', sa.String(length=50), nullable=True),
    sa.Column('last_modified_user_id', sa.String(length=50), nullable=True),
    sa.Column('force_change_password', sa.Boolean(), nullable=True),
    sa.Column('created_user_id', sa.String(length=50), nullable=True),
    sa.Column('last_modified_user_id', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_created_date'), 'user', ['created_date'], unique=False)
    op.create_index(op.f('ix_user_created_user_id'), 'user', ['created_user_id'], unique=False)
    op.create_index(op.f('ix_user_last_modified_user_id'), 'user', ['last_modified_user_id'], unique=False)
    op.create_table('group',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('created_date', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('modified_date', mysql.INTEGER(unsigned=True), nullable=True),
    sa.Column('last_modified_user', sa.String(length=50), nullable=True),
    sa.Column('created_user', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['created_user'], ['user.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['last_modified_user'], ['user.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_group_created_date'), 'group', ['created_date'], unique=False)
    op.create_table('redis',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('jti', sa.String(length=200), nullable=True),
    sa.Column('encoded_token',  sa.Text(), nullable=True),
    sa.Column('expires', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id', 'user_id')
    )
    op.create_table('role',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('type', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('created_date', mysql.INTEGER(unsigned=True), nullable=True),
    sa.Column('modified_date', mysql.INTEGER(unsigned=True), nullable=True),
    sa.Column('last_modified_user', sa.String(length=50), nullable=True),
    sa.Column('created_user', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['created_user'], ['user.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['last_modified_user'], ['user.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_setting',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('display_column', sa.JSON(), nullable=True),
    sa.Column('created_date', mysql.INTEGER(unsigned=True), nullable=True),
    sa.Column('modified_date', mysql.INTEGER(unsigned=True), nullable=True),
    sa.Column('user_id', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_setting_created_date'), 'user_setting', ['created_date'], unique=False)
    op.create_index(op.f('ix_user_setting_user_id'), 'user_setting', ['user_id'], unique=False)
    op.create_table('role_permission',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('permission_id', sa.String(length=50), nullable=False),
    sa.Column('role_id', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permission.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'permission_id', 'role_id')
    )
    op.create_table('user_group_role',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=True),
    sa.Column('group_id', sa.String(length=50), nullable=True),
    sa.Column('role_id', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], onupdate='CASCADE', ondelete='CASCADE')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_group_role')
    op.drop_table('role_permission')
    op.drop_index(op.f('ix_user_setting_user_id'), table_name='user_setting')
    op.drop_index(op.f('ix_user_setting_created_date'), table_name='user_setting')
    op.drop_table('user_setting')
    op.drop_table('role')
    op.drop_table('redis')
    op.drop_index(op.f('ix_group_created_date'), table_name='group')
    op.drop_table('group')
    op.drop_index(op.f('ix_user_last_modified_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_created_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_created_date'), table_name='user')
    op.drop_table('user')
    op.drop_table('permission')
    op.drop_table('message')
    # ### end Alembic commands ###
