"""empty message

Revision ID: 37962ebc0496
Revises: 0de7655d5ab8
Create Date: 2023-08-28 13:51:49.475987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37962ebc0496'
down_revision = '0de7655d5ab8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('message_id', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message', 'message_id')
    # ### end Alembic commands ###
