"""empty message

Revision ID: 61b9acc7c60b
Revises: b2e8207a530f
Create Date: 2023-08-29 09:33:16.358742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61b9acc7c60b'
down_revision = 'b2e8207a530f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('created_user', sa.String(length=50), nullable=True))
    op.add_column('message', sa.Column('last_modified_user', sa.String(length=50), nullable=True))
    op.create_foreign_key(None, 'message', 'user', ['created_user'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    op.create_foreign_key(None, 'message', 'user', ['last_modified_user'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'message', type_='foreignkey')
    op.drop_constraint(None, 'message', type_='foreignkey')
    op.drop_column('message', 'last_modified_user')
    op.drop_column('message', 'created_user')
    # ### end Alembic commands ###
