"""redis_model

Revision ID: 7e62cbf0e709
Revises: f0684cc0e2dc
Create Date: 2023-08-18 13:41:57.193410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e62cbf0e709'
down_revision = 'f0684cc0e2dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('redis',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('jti', sa.String(length=200), nullable=True),
    sa.Column('encoded_token', sa.String(length=200), nullable=True),
    sa.Column('expires', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id', 'user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('redis')
    # ### end Alembic commands ###
