"""empty message

Revision ID: b1f8f95b2d27
Revises: 735d15d88441
Create Date: 2023-08-30 16:03:21.002106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1f8f95b2d27'
down_revision = '735d15d88441'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('block_token', sa.Column('is_block', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('block_token', 'is_block')
    # ### end Alembic commands ###
