"""empty message

Revision ID: fef0a436fa61
Revises: 61b9acc7c60b
Create Date: 2023-08-30 17:04:47.714747

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fef0a436fa61'
down_revision = '61b9acc7c60b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('token',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('jti', sa.String(length=50), nullable=False),
    sa.Column('expires', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('encoded_token', sa.Text(), nullable=False),
    sa.Column('is_block', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('token')
    # ### end Alembic commands ###
