version: "3"

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      ENV: ${ENV}
    command: gunicorn --workers=3 --threads=1 -b 0.0.0.0:5000 --log-level=debug server:app
    ports:
      - "5000:5000"
    networks:
      - btest-template-net

networks:
  btest-template-net:
    name: btest-template-net