version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      ENV: 'dev'
    command: gunicorn --workers=3 --threads=1 -b 0.0.0.0:5012 --preload --log-level=debug server:app
    ports:
      - "5012:5012"
    networks:
      - code-base-net
    volumes:
      - ./:/code-base

  socket:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      FLASK_DEBUG: 1
      FLASK_ENV: development
      FLASK_APP: server.py
    ports:
      - '5000:5000'
    command: gunicorn --workers=1 --threads=1 -b 0.0.0.0:5000 --preload --log-level=debug server:app
    networks:
      - code-base-net
    volumes:
      - ./:/code-base-socket
  redis:
    image: redis:6.2-alpine
    container_name: redis_base_stg
    restart: always
    command: redis-server --save 20 1 --loglevel warning --requirepass cuong-boot-ai
    ports:
      - "6379:6379"
    volumes:
      - cache:/data
    networks:
      - code-base-net
  db:
    image: mysql:8.0
    container_name: mysql_base_stg
    command:
      - --default-authentication-plugin=mysql_native_password
      - --sql_mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: cuong942002
      SQLALCHEMY_TRACK_MODIFICATIONS : True
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init_db/init_mysql/init_files/init.sql:/docker-entrypoint-initdb.d/init.sql
#    networks:
#      - code-base-net
networks:
  code-base-net:
    driver: bridge
    name: code-base-net

volumes:
  db_data:
  cache: