version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      ENV: ${ENV}
    command: ["python", "server.py"]
    ports:
      - "5012:5012"
    networks:
      - source-code-base-net
    volumes:
      - ./:/source-code-base
#  mysql:
#    image: mysql
#    ports:
#      - "5012:5012"
#    networks:
#      - source-code-base-net
networks:
  source-code-base-net:
    name: source-code-base-net