version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      ENV: ${ENV}
    command: gunicorn --workers=3 --threads=1 -b 0.0.0.0:5012 --preload --log-level=debug server:app
    ports:
      - "5012:5012"
    networks:
      - source-code-base-net
    volumes:
      - ./:/source-code-base
  redis:
    image: redis:6.2-alpine
    container_name: redis_base_stg
    restart: always
    command: ["redis-server", "/usr/local/etc/redis/redis.windows.conf"]
    environment:
      REDIS_DB: 1
      REDIS_PASSWORD: 'cuong-boot-ai'
    ports:
      - "6379:6379"
    volumes:
      -  C:\redis\Redis-x64-3.0.504:/usr/local/etc/redis
    networks:
      - source-code-base-net


  db-stg:
    image: mysql:8.0
    container_name: mysql_base_stg
    command:
      - --default-authentication-plugin=mysql_native_password
      - --sql_mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION
    restart: always
    environment:

      MYSQL_ROOT_PASSWORD: G-^rqEyhE6p=A#u*RU:V9J6-
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init_db/init_mysql/init_files/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - source-code-base-net
networks:
  source-code-base-net:
    name: source-code-base-net

volumes:
  db_data: