version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      ENV: ${ENV}
    command: gunicorn --workers=3 --threads=1 -b 0.0.0.0:5012 --preload --log-level=debug server:app
    ports:
      - "5012:5012"
    networks:
      - source-code-base-net
    volumes:
      - ./:/source-code-base
networks:
  source-code-base-net:
    name: source-code-base-net